# Generated by Django 5.1.1 on 2025-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postimg',
            field=models.ImageField(blank=True, default='', upload_to='images/postimgs/'),
        ),
    ]
