# Generated by Django 5.1.1 on 2025-02-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('birth', models.DateField(blank=True, default='1000-01-01')),
                ('phone', models.TextField(blank=True, default='010-0000-0000')),
                ('families', models.TextField(blank=True, default='')),
                ('nation', models.TextField(blank=True, default='Earth')),
                ('legion', models.TextField(blank=True, default='Earth')),
                ('job', models.TextField(blank=True, default='')),
                ('jobaddr', models.TextField(blank=True, default='')),
                ('profileimg', models.TextField(blank=True, default='')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
