# Generated by Django 5.1.1 on 2025-01-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('birth', models.DateField(blank=True, default='')),
                ('phone', models.TextField(blank=True, default='')),
                ('families', models.TextField(blank=True, default='')),
                ('nation', models.TextField(blank=True, default='')),
                ('legion', models.TextField(blank=True, default='')),
                ('job', models.TextField(blank=True, default='')),
                ('jobaddr', models.TextField(blank=True, default='')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
