# Generated by Django 5.1.1 on 2025-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profileimg',
            field=models.ImageField(blank=True, default='', upload_to='images/profiles/'),
        ),
    ]
